import json
import cryptography
from cryptography.hazmat.primitives.kdf.scrypt import Scrypt
import os

from menu_script import menu
from cryptography_functions import load_users
from cryptography_functions import chachapoly_encrypt
from cryptography_functions import chachapoly_decrypt
from cryptography_functions import create_user_file
from cryptography_functions import sign
from cryptography_functions import verify_sign




FILE = 'users.json' #this is the file we will be working on

user, a, chachakey_hex, pwd_byte = menu(FILE)

while a:
    c = input("Do you wish to make a reservation (A), check your reservations (B) or exit (E): " )
    if c == "E" or c == 'e':
        a = False
    elif c == "A" or c == 'a':
        chachakey_byte = bytes.fromhex(chachakey_hex)
        room = int(input("Book room number: "))
        room = str(room)
        time = input("At time: ")
        sign(user, room, time, pwd_byte)

        room_byte = room.encode("utf-8")
        room_enc, nonceroom = chachapoly_encrypt(room_byte, chachakey_byte)
        room_hex = room_enc.hex()
        nonceroom_hex= nonceroom.hex()
        time_byte = time.encode("utf-8")
        time_enc, noncetime = chachapoly_encrypt(time_byte, chachakey_byte)
        time_hex = time_enc.hex()
        noncetime_hex = noncetime.hex()
        create_user_file(user, room_hex, nonceroom_hex, time_hex, noncetime_hex)
    elif c == "B" or c == 'b':
        reservations = load_users(user + '.json')
        for j in range(len(reservations[user])):
            chachakey_byte = bytes.fromhex(chachakey_hex)
            room_enc = bytes.fromhex(reservations[user][j][0])
            nonceroom_byte = bytes.fromhex(reservations[user][j][1])
            room_byte = chachapoly_decrypt(chachakey_byte, room_enc, nonceroom_byte)
            room = room_byte.decode('utf-8')
            time_enc = bytes.fromhex(reservations[user][j][2])
            noncetime_byte = bytes.fromhex(reservations[user][j][3])
            time_byte = chachapoly_decrypt(chachakey_byte, time_enc, noncetime_byte)
            time = time_byte.decode('utf-8')
            print('Reservation ', j+1, ':\nRoom:', room, '\nTime:', time)
            verify = str(input("Do you wish to verify this info?(Y/N): "))
            if verify == 'Y' or verify == 'y':
                json_f = user + room + time + '.json'
                pem_public = user + room + time + 'public.pem'
                verified = verify_sign(json_f, pem_public)

#HAVE TO IMPLEMENT PKI
#the public key will be from inside the certificate, not "raw" in publickey.pem
# also have to verify the signature on the certificate (generated by the certification authority)
# have to use the public key of the certification authority to verify
# you have to attach this certificate to your signature, and the CA certificate (which will contain the public key needed to verify your certificate) generated by the command to your certificate
# cert.public_key() has the public key for the data
# cert_CA.public_key() has the public key to verify your certificate's signature
# cert_CA.public_key() has the public key to verify its own signature 
#have to use option 2b to create the certificate and 2c to verify


#as of 01-01, there's only verification left to implement and draw the public key for the other verification
#(of the signature) from it